### ISSUE TITLE
XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by Odalrick** [ospfranco/react-native-link-preview#40]
It looks like https://github.com/ospfranco/react-native-link-preview/pull/29 broke support for node, specifically since XMLHttpRequest isn't a built-in for node. 

I'm using  v1.2.1 for now.

**Comment by Odalrick** [comment]
Some digging; I thought a pull request would be simple to put together:

It appears the latest release from the github, https://github.com/ospfranco/react-native-link-preview/tree/v1.3.5 works in node; but not the latest release from npm 1.3.7 …

**Comment by scottmas** [comment]
Yeah, why change this away from fetch? Fetch has great support, and this library isn't even _targeting_ browsers.

**Comment by ospfranco** [comment]
Actually the problem was fetch, on certain samsung models the fetch api simply crashes applications (and thanks to android fragmentation this models will never be patched).

Also if you read the readme, node support was added quite a while ago, so naming has stayed, but it is targeted and react-native projects and non-browser node environments.

I think I will add axios as a dependency, for the afore mentioned issues, unless any one has a complaint.

**Comment by scottmas** [comment]
Yeah that's a great idea to use axios. Do you have the specific model though? Axios most likely just checks for the existence of fetch, it doesn't know that using it will cause a crash.

**Comment by ospfranco** [comment]
I started applying the changes to the project when I realized the PR I merged that got rid of fetch in favor of XMLHttpRequest broke the tests, I will be more careful accepting PRs in the future, after fumbling around for a bit trying to get everything working again, I decided that trying to replace fetch for an older implementation is a stupid idea anyways, the bug is on react-native side, for now I suggest if you ever find an issue on a samsung device to handle the error gracefully.

**Comment by ospfranco** [comment]
I also tried to use axios, but it seems underneath it uses xmlhttprequest, for some reason I keep getting cors errors, either my node version now does CORS check or some other library in-between, anyways, fetch seems to be the only one which works.
